#What is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

#Numpy Arrays Vs Python Sequences
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.


```

```



# Creating Numpy Arrrays

In [1]:
#np.array

import numpy as np
a = np.array([1,2,3])

In [2]:
print(a)

[1 2 3]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
#2D Array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
#3D Array and Tensor array
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [13]:
#dtype array
d = np.array([1,3,4],dtype=float)
print(d)
e = np.array([5,6,7],dtype=bool)
print(e)
cmplx = np.array([2,3,4],dtype=complex)
print(cmplx)

[1. 3. 4.]
[ True  True  True]
[2.+0.j 3.+0.j 4.+0.j]


In [14]:
#np.arange work like arrange
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [17]:
b = np.arange(1,10,2)

In [18]:
print(b)

[1 3 5 7 9]


In [21]:
#np.reshape
b = np.arange(1,11).reshape(5,2)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [26]:
#np.ones
a = np.ones((3,4))
print(a)

b = np.zeros((3,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
#np.random
np.random.random((3,4))

array([[0.61486998, 0.85643627, 0.1298601 , 0.7894594 ],
       [0.7830085 , 0.78753487, 0.64001545, 0.75574041],
       [0.40346559, 0.21954753, 0.33300645, 0.45809994]])

In [28]:
#np.linspace
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [29]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attribute

In [32]:
#ndim number of dimension

b.ndim

2

In [31]:
c.ndim

3

In [35]:
print(c.shape)
print(c)

(1, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [36]:
c.size

9

In [37]:
c.itemsize

8

# Changing Datatype

In [40]:
#astype
c = c.astype(np.int32)

In [41]:
c.itemsize

4

# Array Operation

In [42]:
a1 = np.arange(12).reshape((3,4))
a2 = np.arange(12,24).reshape((3,4))

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
# Scalar Operation

#arithmetic
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [44]:
# relational
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [45]:
#vector operation
#arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# Array Function

In [46]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[81., 15., 59.],
       [24., 17., 33.],
       [92., 18., 85.]])

In [47]:
np.max(a1)

np.float64(92.0)

In [48]:
np.min(a1)

np.float64(15.0)

In [50]:
np.prod(a1)

np.float64(135856884398400.0)

In [51]:
np.sum(a1)

np.float64(424.0)

In [52]:
#0 -> column and row->1
np.max(a1,axis=1)

array([81., 33., 92.])

In [53]:
np.max(a1,axis=0)

array([92., 18., 85.])

In [54]:
np.mean(a1)

np.float64(47.111111111111114)

In [55]:
np.median(a1)

np.float64(33.0)

In [58]:
np.var(a1)

np.float64(917.6543209876543)

In [59]:
np.std(a1)

np.float64(30.29280972421763)

In [61]:
# dot product
a1 = np.arange(12).reshape((3,4))
a2 = np.arange(12,24).reshape((4,3))

np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [62]:
np.log(a1)

/tmp/ipython-input-2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [63]:
np.round(np.random.random((2,3))*100)

array([[10., 98., 36.],
       [55., 41., 64.]])

# Indexing and Slicing

In [64]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [65]:
a1[-1]

np.int64(9)

In [66]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a2[1,2]

np.int64(6)

In [68]:
a2[1,0]

np.int64(4)

In [69]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [70]:
a3[1,0,1]

np.int64(5)

In [71]:
a3[0,0,0]

np.int64(0)

In [72]:
a1[2:5]

array([2, 3, 4])

In [73]:
a1[2:5:2]

array([2, 4])

In [74]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
a2[0,:]

array([0, 1, 2, 3])

In [77]:
a2[1:3,2]

array([ 6, 10])

# Iterating

In [81]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [85]:
a2
for i in np.nditer(a2):
  print(i)


0
1
2
3
4
5
6
7
8
9
10
11


In [80]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Transpose

In [89]:
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [90]:
# ravel make the dimenstion to 1d array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking



In [92]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [93]:
np.hstack((a4,a5))  # horizontal stacking means joint 2 matrix horizontaly

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [94]:
#vertical
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

 # Split

In [97]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [98]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]