# np sort

In [ ]:
import numpy as np
a= np.random.randint(1,100,15)
a

array([46, 72,  8,  2, 76, 31, 99, 25, 42, 12, 90,  9, 21, 80, 36])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 3, 31, 44, 63],
       [19, 39, 37, 65],
       [60, 72, 98,  8],
       [33, 87, 29, 44],
       [57, 51, 47, 17],
       [ 2, 82, 23, 43]])

In [ ]:
np.sort(a)

array([ 2,  8,  9, 12, 21, 25, 31, 36, 42, 46, 72, 76, 80, 90, 99])

In [ ]:
np.sort(b)

array([[ 3, 31, 44, 63],
       [19, 37, 39, 65],
       [ 8, 60, 72, 98],
       [29, 33, 44, 87],
       [17, 47, 51, 57],
       [ 2, 23, 43, 82]])

In [ ]:
np.sort(b,axis=0)

array([[ 2, 31, 23,  8],
       [ 3, 39, 29, 17],
       [19, 51, 37, 43],
       [33, 72, 44, 44],
       [57, 82, 47, 63],
       [60, 87, 98, 65]])

In [ ]:
np.append(a,200)

array([ 46,  72,   8,   2,  76,  31,  99,  25,  42,  12,  90,   9,  21,
        80,  36, 200])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 3., 31., 44., 63.,  1.],
       [19., 39., 37., 65.,  1.],
       [60., 72., 98.,  8.,  1.],
       [33., 87., 29., 44.,  1.],
       [57., 51., 47., 17.,  1.],
       [ 2., 82., 23., 43.,  1.]])

In [ ]:
# np concatenate
c = np.arange(6).reshape((2,3))
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# np.unique

In [ ]:
e = np.array([1,1,2,3,4,2,3,5,6,8])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 8])

# np.expand_dim

In [ ]:
a

array([46, 72,  8,  2, 76, 31, 99, 25, 42, 12, 90,  9, 21, 80, 36])

In [ ]:
np.expand_dims(a,axis=1)

array([[46],
       [72],
       [ 8],
       [ 2],
       [76],
       [31],
       [99],
       [25],
       [42],
       [12],
       [90],
       [ 9],
       [21],
       [80],
       [36]])

In [ ]:
np.expand_dims(a,axis=1).shape

(15, 1)

# np.where

return the idex pos

In [ ]:
a

array([46, 72,  8,  2, 76, 31, 99, 25, 42, 12, 90,  9, 21, 80, 36])

In [ ]:
np.where(a>50)

(array([ 1,  4,  6, 10, 13]),)

In [ ]:
#replace all value where values > 50 with 0
#np.where(condition,true,false)

np.where(a>50,0,a)

array([46,  0,  8,  2,  0, 31,  0, 25, 42, 12,  0,  9, 21,  0, 36])

In [ ]:
np.where(a%2==0,0,a)

array([ 0,  0,  0,  0,  0, 31, 99, 25,  0,  0,  0,  9, 21,  0,  0])

# np.argmax
return the index of max ele

In [ ]:
np.argmax(a)

np.int64(6)

In [ ]:
np.argmax(b,axis=0)

array([2, 3, 2, 1])

In [ ]:
b

array([[ 3, 31, 44, 63],
       [19, 39, 37, 65],
       [60, 72, 98,  8],
       [33, 87, 29, 44],
       [57, 51, 47, 17],
       [ 2, 82, 23, 43]])

In [ ]:
np.argmin(a)

np.int64(3)

# np.cumsum

return cumulative sum

In [ ]:
a

array([46, 72,  8,  2, 76, 31, 99, 25, 42, 12, 90,  9, 21, 80, 36])

In [ ]:
np.cumsum(a)

array([ 46, 118, 126, 128, 204, 235, 334, 359, 401, 413, 503, 512, 533,
       613, 649])

In [ ]:
np.cumsum(b)

array([   3,   34,   78,  141,  160,  199,  236,  301,  361,  433,  531,
        539,  572,  659,  688,  732,  789,  840,  887,  904,  906,  988,
       1011, 1054])

In [ ]:
b

array([[ 3, 31, 44, 63],
       [19, 39, 37, 65],
       [60, 72, 98,  8],
       [33, 87, 29, 44],
       [57, 51, 47, 17],
       [ 2, 82, 23, 43]])

In [ ]:
np.cumsum(b,axis=0)

array([[  3,  31,  44,  63],
       [ 22,  70,  81, 128],
       [ 82, 142, 179, 136],
       [115, 229, 208, 180],
       [172, 280, 255, 197],
       [174, 362, 278, 240]])

In [ ]:
np.cumprod(a)

array([                  46,                 3312,                26496,
                      52992,              4027392,            124849152,
                12360066048,         309001651200,       12978069350400,
            155736832204800,    14016314898432000,   126146834085888000,
        2649083515803648000,  9012496453486772224, -7591521001248129024])

# Percentaile

In [ ]:
a

array([46, 72,  8,  2, 76, 31, 99, 25, 42, 12, 90,  9, 21, 80, 36])

In [ ]:
np.percentile(a,100)

np.float64(99.0)

In [ ]:
np.percentile(a,50)

np.float64(36.0)

In [40]:
np.percentile(a,0)

np.float64(2.0)

# np.histogram

In [41]:
a

array([46, 72,  8,  2, 76, 31, 99, 25, 42, 12, 90,  9, 21, 80, 36])

In [42]:
np.histogram(a,bins=[0,10,100])

(array([ 3, 12]), array([  0,  10, 100]))

In [43]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([3, 1, 2, 2, 2, 0, 0, 2, 1, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef

In [45]:
slary = np.array([20000,30000,40000,50000])
experience = np.array([1,2,3,4])

np.corrcoef(slary,experience)

array([[1., 1.],
       [1., 1.]])

# np.isin

In [46]:
a

array([46, 72,  8,  2, 76, 31, 99, 25, 42, 12, 90,  9, 21, 80, 36])

In [47]:
items = [10,20,30,40,50,60]
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [48]:
a[np.isin(a,items)]

array([], dtype=int64)

# Flip

In [49]:
a

array([46, 72,  8,  2, 76, 31, 99, 25, 42, 12, 90,  9, 21, 80, 36])

In [50]:
np.flip(a)

array([36, 80, 21,  9, 90, 12, 42, 25, 99, 31, 76,  2,  8, 72, 46])

# np.put|

In [51]:
a

array([46, 72,  8,  2, 76, 31, 99, 25, 42, 12, 90,  9, 21, 80, 36])

In [52]:
np.put(a,[0,1],[110,50])

In [53]:
a

array([110,  50,   8,   2,  76,  31,  99,  25,  42,  12,  90,   9,  21,
        80,  36])

# delete

In [54]:
np.delete(a,0)

array([50,  8,  2, 76, 31, 99, 25, 42, 12, 90,  9, 21, 80, 36])

In [55]:
np.delete(a,[0,2,4])

array([50,  2, 31, 99, 25, 42, 12, 90,  9, 21, 80, 36])

# Set Function

In [56]:
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])



In [57]:
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7])

In [58]:
np.intersect1d(a,b)

array([3, 4, 5])

In [59]:
np.setdiff1d(a,b)

array([1, 2])

In [60]:
np.setxor1d(a,b)

array([1, 2, 6, 7])

In [61]:
np.in1d(a,2)

/tmp/ipython-input-1646599517.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(a,2)


array([False,  True, False, False, False])

In [62]:
a[np.in1d(a,2)]

/tmp/ipython-input-2988045372.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  a[np.in1d(a,2)]


array([2])

# np clip give the value

In [64]:
np.clip(a,a_max=4,a_min=2)

array([2, 2, 3, 4, 4])